CREATE USER `next`
CREATE DATABASE IF NOT EXISTS `next`;
GRANT ALL PRIVILEGES ON DATABASE `next` TO `next`;
GRANT ALL PRIVILEGES ON DATABASE `next` TO postgres;
CREATE DATABASE IF NOT EXISTS postgres;
GRANT ALL PRIVILEGES ON DATABASE postgres TO `next`;
ALTER USER `next` PASSWORD 'next';

-- CREATE EXTENSION pg_trgm schema pg_catalog;
