CREATE DATABASE IF NOT EXISTS nextjs;
CREATE USER nextjs WITH PASSWORD 'nextjs';
GRANT ALL PRIVILEGES ON DATABASE nextjs TO nextjs;
GRANT ALL PRIVILEGES ON DATABASE nextjs TO postgres;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA nextjs;
